# Generated by Django 5.1.2 on 2024-11-13 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('CPF', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nasc', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('tel_paciente', models.CharField(max_length=15)),
                ('tel_responsavel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.AutoField(primary_key=True, serialize=False)),
                ('setor', models.CharField(max_length=50)),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_func', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('is_medico', models.BooleanField(default=False)),
                ('senha', models.CharField(max_length=128)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id_exame', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Exame_paciente',
            fields=[
                ('id_exame_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora_realizacao', models.DateTimeField(auto_now_add=True)),
                ('data_hora_retirada', models.DateTimeField(null=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.exame')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta_medico_paciente',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('sintomas', models.TextField()),
                ('prescricao_medica', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('doenca', models.CharField(blank=True, max_length=100)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.funcionario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcao_funcionario_paciente',
            fields=[
                ('id_recepcao', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.funcionario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.paciente')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Triagem_medico_paciente',
            fields=[
                ('id_triagem', models.AutoField(primary_key=True, serialize=False)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('pressao_sistolica', models.IntegerField()),
                ('pressao_diastolica', models.IntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.funcionario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.paciente')),
            ],
        ),
    ]
