# Generated by Django 5.1.2 on 2024-11-22 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalCC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcar_consulta',
            fields=[
                ('id_marcacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora_marcacao', models.DateTimeField(auto_now_add=True)),
                ('data_hora_consulta', models.DateTimeField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.funcionario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalCC.paciente')),
            ],
        ),
    ]
